chores(eslint): add eslint & lint all files
FashionData/maestro pull request #205
Opened 2023-01-20 09:38 UTC by Cosme711

## Description

I added eslint & configured it exactly like in customer autopilot. I lint all the files automatically. Most changes are just indentation or formatting.

## What does this PR do?

- [ ] Add eslint packages
- [ ] Update default config
- [ ] Lint all files

2023-01-23 09:54 UTC, Eronne requested changes

2023-01-23 09:54 UTC, Eronne commented on .editorconfig
> +
Il faudrait que ce fichier soit utilisé ensuite dans les apps qui consomme Maestro comme on disait.

2023-01-23 09:54 UTC, Eronne commented on .eslintrc.js
> +};
Il faudrait que ce fichier soit utilisé ensuite dans les apps qui consomme Maestro comme on disait.

2023-01-23 09:54 UTC, Eronne commented on babel.config.js
> +}
Il faudrait que ce fichier soit utilisé ensuite dans les apps qui consomme Maestro comme on disait.

2023-01-23 09:54 UTC, Eronne commented on vue.config.js
> +}
Il faudrait que ce fichier soit utilisé ensuite dans les apps qui consomme Maestro comme on disait.

2023-01-24 16:19 UTC, Eronne requested changes

2023-01-24 16:19 UTC, Eronne commented on package.json
> +    "eslint-config-fashiondata": "git+https://github.com/FashionData/eslint-config-fashiondata",
J'aurais juste rename le nom de la dépendance et le repo :

```suggestion
    "@fashiondata/eslint-config": "git+https://github.com/FashionData/eslint-config",
```

2023-01-25 17:19 UTC, Eronne reviewed
Il va juste rester le rename du package que tu peux voir dans la discussion juste au-dessus.

2023-01-31 10:06 UTC, Cosme711 commented on package.json
> +    "eslint-config-fashiondata": "git+https://github.com/FashionData/eslint-config-fashiondata",
Done

2023-01-31 13:09 UTC, Eronne approved these changes

2023-01-31 13:10 UTC, merged