WIP: fix(logout): update logout functions
FashionData/maestro pull request #208
Opened 2023-02-02 18:39 UTC by Cosme711

2023-02-06 10:21 UTC, Eronne requested changes

2023-02-06 10:21 UTC, Eronne commented on src/components/layouts/logged-in/disabled-account.vue
> +      }
C'est exactement le même code que dans la méthode `logout` de `src/components/layouts/logged-in/container-component.vue`.

Il y aurait moyen de la rappeler ?

Parce que du coup si on rajoute un endroit où se logout, il faudra encore copier / coller ce code.

2023-03-24 17:56 UTC, Eronne requested changes

2023-03-24 17:56 UTC, Eronne commented on src/store/user/index.ts
> +import { router } from '../../../dev/main'
Là il y a un souci, tu importes le router du playground (dossier `dev`) dans le package maestro (dossier `src`).

2023-03-24 17:56 UTC, Eronne commented on src/store/user/index.ts
> +      })
Il faudrait gérer le fait que `signOut()` est une Promise.

Dans la doc tu peux le voir ici => https://firebase.google.com/docs/auth/web/password-auth

2023-03-24 17:56 UTC, Eronne commented on dev/main.ts
> +export const router = new VueRouter({ mode: "history", routes });
```suggestion
const router = new VueRouter({ mode: "history", routes });
```

2023-03-27 08:21 UTC, Cosme711 commented on src/store/user/index.ts
> +import { router } from '../../../dev/main'
Enfaite j'avais des diffcultés pour appeler le router dans le store. J'ai enlevé cette import et ajouté la redirection dans le resolve où la fonction logout est appelé ( je me suis inspiré de authenticateUser dans login-mixin ) mais si tu as une meilleure solution pour importer le router dans le store, je suis preneur :)

2023-03-28 12:43 UTC, Eronne commented on src/store/user/index.ts
> +import { router } from '../../../dev/main'
A tester avec `onAuthStateChanged` comme on s'est dit en point 😉

2023-03-28 16:08 UTC, Eronne approved these changes

2023-03-30 12:06 UTC, merged