Feat/211 - m-display-value component
FashionData/maestro pull request #212
Opened 2023-03-24 14:05 UTC by Cosme711

## Related issue(s)

#211

2023-04-12 08:23 UTC, Eronne requested changes

2023-04-12 08:23 UTC, Eronne commented on src/components/m-display-value.vue
> +type SignType = "euro" | "percent" | "point" | "null"
J'aurais plutôt parlé de `currency` parce qu'on peut avoir des marques qui ne bossent pas en euro.

```suggestion
type SignType = "currency" | "percent" | "point" | "null"
```

2023-04-12 08:23 UTC, Eronne commented on src/components/m-display-value.vue
> +  style?: string,
Elles servent à quoi ces 2 propriétés ? Elles n'ont pas l'air d'être utilisées quelque part.

2023-04-12 08:23 UTC, Eronne commented on src/components/m-display-value.vue
> +    return this.plusSign + this.$n(number, options) + this.formatedSignType
Il manque une indentation là non ?

2023-04-12 08:23 UTC, Eronne commented on src/components/m-display-value.vue
> +    const number = roundNumber(this.value * type, 2)
Le type ça m'a paru bizarre que ce soit un nombre. Est-ce qu'un truc comme ça ne serait pas plus compréhensible a premier abord ?

```suggestion
    let type = 1
    if(this.signType === 'percent') type = 100
    const number = roundNumber(this.signType === 'percent' ? this.value * 100 : this.value, 2)
```

2023-04-12 08:23 UTC, Eronne commented on src/components/m-display-value.vue
> +    const number = roundNumber(this.value * type, 2)
Le fait d'arrondir à 2 ici ne rentre pas en conflit avec la props `digitsAfterDecimal` ?

2023-04-12 08:23 UTC, Eronne commented on src/components/m-display-value.vue
> +      else return "";
```suggestion
      if (!this.showColors || !this.value || this.value === 0) return "";
      else if (this.value < 0) return "negative";
      else return "positive";
```

2023-04-12 08:23 UTC, Eronne commented on src/components/m-display-value.vue
> +          return '%'
Pareil ici on peut aussi utiliser i18n.

2023-04-12 08:23 UTC, Eronne commented on src/components/m-display-value.vue
> +          return 'pts'
Il faudrait une traductions ici ou je me demande s'il ne faudrait pas laisser la possibilité au use de mettre une unité custom.

Demain si on parle en quantité ou autre, ça veut dire qu'il va falloir le gérer ici alors que ce n'est pas forcément nécessaire.

2023-04-12 11:11 UTC, Cosme711 commented
En regardant tes retours, j'ai encore plus simplifié le composant. 
À présent, le signType "currency" affiche le signe correspondant i18n, "%" multiplie la valeur par 100 et affiche le signe après. Toute autre valeur passée dans signType est prise comme un signe "custom" et s'affiche simplement après.

2023-04-13 13:58 UTC, Eronne requested changes

2023-04-13 15:52 UTC, Eronne commented on shims-vue.d.ts
> +    $roundToTwoDecimals: (numberToRound: number) => number;
T'as un petit espace ici

2023-04-13 15:56 UTC, merged